### PR TITLE
Add possibility to accept non 200 http status code in response

### PR DESCRIPTION
**Pull request by jgiacomini**
Add the possibility to accept non http2xx status codes. 
#80

### CODE REVIEW

**Comment by jgiacomini** [comment]
#80

**Comment by guillaumechervetaxa** [comment]
Great new :) Thank you very much!
Do you have some Unit Test associated? Because I 'am not inside your project, I will understand more your code with some tests.

**Comment by jgiacomini** [comment]
I have updated the readme => you can see how to use it.

After you validate it I will write somes tests :)

**Comment by jgiacomini** [comment]
### Allow non http 2xx responses

Allow all status code :
```cs
client.Settings.HttpStatusCodeAllowed.AllowAllStatus = false;
```

Allow only a range of http status codes :
```cs
client.Settings.HttpStatusCodeAllowed.Add(new HttpStatusRange(400, 420));
```

**Review by Lordinaire — APPROVED** [review]

**Comment by Lordinaire** [comment]
By default, I prefer to set AllowAllStatus to true.

**Comment by jgiacomini** [comment]
> 
> 
> By default, I prefer to set AllowAllStatus to true.

It's a good point haha.

I will change that

**Comment by jgiacomini** [comment]
I have to implements methods + tests and after I merge it :)

**Comment by jgiacomini** [comment]
After 6 months of inactivity (sorry for that) the PR is ready.
Anyone to review it?

**Pull request merged**
